Repository CityOfStanton/Kiosk-Client, pull requests merged in 2021-01, with the labels that each got.

#18 Bug Fix - Fixed crash on empty URL
  src/KioskClient/Pages/Settings.xaml.cs
Labels: bug

#21 Code refinements
  KioskClient.sln
  src/KioskClient/App.xaml.cs
  src/KioskClient/Converters/InvertBooleanConverter.cs
  src/KioskClient/KioskClient.csproj
  src/KioskClient/MainPage.xaml
  src/KioskClient/MainPage.xaml.cs
  src/KioskClient/Pages/Actions/ImagePage.xaml.cs
  src/KioskClient/Pages/Actions/WebsitePage.xaml.cs
  src/KioskClient/Pages/PageArguments/SettingsPageArguments.cs
  src/KioskClient/Pages/PagesHelper.cs
  src/KioskClient/Pages/Settings.xaml
  src/KioskClient/Pages/Settings.xaml.cs
  src/KioskClient/ViewModels/SettingsViewModel.cs
  src/KioskClient/ViewModels/ViewModel.cs
  src/KioskLibrary/Actions/Action.cs
  src/KioskLibrary/Actions/ImageAction.cs
  src/KioskLibrary/Actions/WebsiteAction.cs
  src/KioskLibrary/Common/Constants.cs
  src/KioskLibrary/Common/OrchestrationSource.cs
  src/KioskLibrary/Common/Ordering.cs
  src/KioskLibrary/Converters/ActionConverter.cs
  src/KioskLibrary/Helpers/HttpHelper.cs
  src/KioskLibrary/Helpers/SerializationHelper.cs
  src/KioskLibrary/KioskLibrary.csproj
  src/KioskLibrary/Orchestration/LifecycleBehavior.cs
  src/KioskLibrary/Orchestration/OrchestrationInstance.cs
  src/KioskLibrary/Orchestration/Orchestrator.cs
  src/KioskLibrary/PageArguments/MainPageArguments.cs
  src/KioskLibrary/Storage/ApplicationStorage.cs
  src/OrchestrationPollingManager/OrchestrationPollingManager.csproj
  src/OrchestrationPollingManager/OrchestrationUpdateTask.cs
  src/OrchestrationPollingManager/Properties/AssemblyInfo.cs
Labels: enhancement

#23 Azure pipelines
  KioskClient.sln
  azure-pipelines.yml
  deployment/KioskClientDeployment/KioskClientDeployment.wapproj
  deployment/KioskClientDeployment/Package.appxmanifest
  src/KioskClient/App.xaml.cs
  src/KioskClient/KioskClient.csproj
  src/KioskClient/Package.appxmanifest
  src/KioskLibrary/Actions/Action.cs
  src/KioskLibrary/Actions/ImageAction.cs
  src/KioskLibrary/Converters/ActionConverter.cs
  src/KioskLibrary/Helpers/SerializationHelper.cs
  src/KioskLibrary/KioskLibrary.csproj
  src/KioskLibrary/Orchestration/OrchestrationInstance.cs
  src/KioskLibrary/Orchestration/Orchestrator.cs
  src/KioskLibrary/Storage/ApplicationStorage.cs
  src/OrchestrationPollingManager/OrchestrationPollingManager.csproj
  test/Common/CommonTestLibrary/CommonTestLibrary.csproj
  test/Unit/KioskClient.Spec/KioskClient.Spec.csproj
  test/Unit/KioskLibrary.Spec/KioskLibrary.Spec.csproj
  test/Unit/OrchestrationPollingManager.Spec/OrchestrationPollingManager.Spec.csproj
Labels: dev-ops, enhancement

#24 Added /p:UapAppxPackageBuildMode=StoreUpload
  azure-pipelines.yml
Labels: dev-ops
